name: Test Translation namespace

on:
  push:
    branches:
      - master
      - feat/test-translations

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4
        with:
          paths_filter: |
            ui_repos:
              paths:
                - '.github/**/*' 
                - 'packages/ps2/public/locales/en/**/*'
                - 'packages/raffles-client/public/locales/en/**/*'

  push_translations:
    needs: pre_job
    # If 'skip-duplicate-actions' terminates before the paths checks are performed (for example, when a successful duplicate run has
    # been found) 'paths_result' outputs an empty object ('{}'). This can be easily intercepted in the if condition of a job
    # by checking the result of the "global" 'should_skip' output first.
    if: needs.pre_job.outputs.should_skip != 'true' || !fromJSON(needs.pre_job.outputs.paths_result).ui_repos.should_skip
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ROBOZIGNALY_PAT }}
          fetch-depth: 0 # better fetch all and rebuild part than to fetch part and rebuild all
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Build translations
        run: node scripts/fix-locales.js
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'packages'
          author_name: Translator
          author_email: alex@xfuturum.com
          committer_name: Translator
          committer_email: alex@xfuturum.com
          message: 'Updated test translations'
